#!/usr/bin/env node
import { execSync } from 'child_process';
import { writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

/**
 * Genererer versjonsinformasjon basert på Git og package.json
 * Kjører automatisk før hver build
 */
function generateVersion() {
  try {
    // Les base version fra package.json
    const versionOutput = execSync('npm pkg get version').toString().trim();
    const baseVersion = JSON.parse(versionOutput) || '0.0.0';

    // Hent Git-informasjon
    const gitCommitCount = execSync('git rev-list --count HEAD').toString().trim();
    const gitCommitHash = execSync('git rev-parse --short HEAD').toString().trim();
    const gitBranch = execSync('git rev-parse --abbrev-ref HEAD').toString().trim();

    // Sjekk om det er uncommitted changes
    let isDirty = false;
    try {
      const gitStatus = execSync('git status --porcelain').toString().trim();
      isDirty = gitStatus.length > 0;
    } catch (e) {
      // Ignorer feil hvis ikke i git repo
    }

    // Hent timestamp
    const buildDate = new Date().toISOString();

    // Konstruer version i format v-0.X (enkelt Git commit count format)
    const simpleVersion = `v-0.${gitCommitCount}`;
    const fullVersion = `${baseVersion}-${gitCommitCount}`;
    const fullVersionWithHash = `${fullVersion}+${gitCommitHash}`;

    // Lag versjonsobjekt
    const versionInfo = {
      version: simpleVersion,           // v-0.9 format (enkelt display)
      fullVersion: fullVersionWithHash, // 1.0.0-9+10c7d67 (detaljert)
      baseVersion: baseVersion,
      buildNumber: parseInt(gitCommitCount),
      commitHash: gitCommitHash,
      branch: gitBranch,
      isDirty: isDirty,
      buildDate: buildDate,
      buildTimestamp: Date.now()
    };

    // Skriv til version.json (runtime tilgjengelig)
    const publicVersionPath = join(__dirname, '..', 'public', 'version.json');
    writeFileSync(publicVersionPath, JSON.stringify(versionInfo, null, 2));

    // Skriv til TypeScript fil (compile-time tilgjengelig)
    const srcVersionPath = join(__dirname, '..', 'src', 'version.ts');
    const tsContent = `// Auto-generated by scripts/generate-version.js
// DO NOT EDIT MANUALLY

export const VERSION_INFO = ${JSON.stringify(versionInfo, null, 2)} as const;

export const VERSION = VERSION_INFO.version;
export const FULL_VERSION = VERSION_INFO.fullVersion;
export const BUILD_NUMBER = VERSION_INFO.buildNumber;
export const COMMIT_HASH = VERSION_INFO.commitHash;
export const BUILD_DATE = VERSION_INFO.buildDate;
`;
    writeFileSync(srcVersionPath, tsContent);

    console.log(`✓ Version generated: ${simpleVersion}`);
    console.log(`  Display: ${simpleVersion}`);
    console.log(`  Full: ${fullVersionWithHash}`);
    console.log(`  Build: ${gitCommitCount}`);
    console.log(`  Commit: ${gitCommitHash}`);
    console.log(`  Branch: ${gitBranch}`);
    console.log(`  Dirty: ${isDirty ? 'YES (uncommitted changes)' : 'NO'}`);

    return versionInfo;
  } catch (error) {
    console.error('Error generating version:', error.message);

    // Fallback version hvis Git ikke er tilgjengelig
    const fallbackVersion = {
      version: '0.0.0-dev',
      fullVersion: '0.0.0-dev+unknown',
      baseVersion: '0.0.0',
      buildNumber: 0,
      commitHash: 'unknown',
      branch: 'unknown',
      isDirty: true,
      buildDate: new Date().toISOString(),
      buildTimestamp: Date.now()
    };

    // Skriv fallback versjon
    const publicVersionPath = join(__dirname, '..', 'public', 'version.json');
    writeFileSync(publicVersionPath, JSON.stringify(fallbackVersion, null, 2));

    const srcVersionPath = join(__dirname, '..', 'src', 'version.ts');
    const tsContent = `// Auto-generated by scripts/generate-version.js
export const VERSION_INFO = ${JSON.stringify(fallbackVersion, null, 2)} as const;
export const VERSION = VERSION_INFO.version;
export const FULL_VERSION = VERSION_INFO.fullVersion;
export const BUILD_NUMBER = VERSION_INFO.buildNumber;
export const COMMIT_HASH = VERSION_INFO.commitHash;
export const BUILD_DATE = VERSION_INFO.buildDate;
`;
    writeFileSync(srcVersionPath, tsContent);

    console.log('⚠ Using fallback version (Git not available)');
    return fallbackVersion;
  }
}

// Kjør hvis scriptet kjøres direkte
generateVersion();
